apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-kafka-credentials
  namespace: default
spec:
  secretTargetRef:

    - parameter: username
      name: api-secrets
      key: api_key
    - parameter: password
      name: api-secrets
      key: api_secret